### ISSUE TITLE
release version explanation

### ISSUE THREAD

**Issue by yogeek** [jtblin/kube2iam#298] opened 2021-01-20 18:13 UTC
In the github [release](https://github.com/jtblin/kube2iam/releases), the last one is `kube2iam-2.5.2` although the previous one was `0.10.11` : did you change the tag convention ? 

It seems that the [hub page](https://hub.docker.com/r/jtblin/kube2iam/tags/?page=1&ordering=last_updated) is showing the new tagging... If i want the latest docker image, do you confirm the versions are now all prefixed by `kube2iam-` ?

I am using https://github.com/jetstack/version-checker to check the last version of tools in my cluster and I would like to know which tag pattern I must watch exactly.
Thanks !

**Comment by wc-s** [comment] 2021-01-21 11:17
Not a maintainer, but it looks like they are trying to have both the application code and the helm chart code in the same repo, and are using two kinds of tagging conventions in order to differentiate between an application code release versus a helm chart release.

**Comment by yogeek** [comment] 2021-01-21 14:02
Hum...ok, thanks for the Intel.
Do you know which one is for the chart and which one for the app ?
But if it concerns only the helm chart, why these different tags are also in docker hub repository ? Charts are not docker images...
Would be nice if someone can explain the whole release process and add this to the documentation maybe...
Thanks

**Comment by wc-s** [comment] 2021-01-21 14:10
`kube2iam-2.5.2` is the tag for chart version 2.5.2: https://github.com/jtblin/kube2iam/compare/0.10.11...kube2iam-2.5.2
`0.10.11` is the tag for the application: https://github.com/jtblin/kube2iam/compare/0.10.10...0.10.11

I assume they have an automated pipeline where they push a new docker image to dockerhub with every tag, even though this new tag `kube2iam-2.5.2` does not contain any application code changes.

**Comment by yogeek** [comment] 2021-01-21 15:09
Ok...thanks.
Not very intuitive 😅
I wonder how the other projects handle this situation.

I guess I have to use a regex to filter docker hub tags to only watch the ones not containing `kube2iam-` then...

**Comment by antoinedeschenes** [comment] 2021-01-21 17:01
One would either use two different GitHub repositories or setup regexes in the CI to build the matching part separately.

The chart was recently migrated from https://github.com/helm/charts to this repo. They probably forgot to set a regex on Docker Hub to ignore the chart tags.

**Comment by walkafwalka** [comment] 2021-01-26 17:14
It is as @antoinedeschenes stated. Unfortunately, I do not have access to the Dockerhub registry, so I cannot address this.

Closing. Duplicate of #297.

**Closed by walkafwalka** 2021-01-26 17:14 UTC
