### ISSUE TITLE
iptables rule added is not deleted once the pod 

### ISSUE THREAD

**Issue by holgerreif** [jtblin/kube2iam#141] opened 2018-05-30 17:18 UTC
While at startup the parameter `--iptables=true`  provides a convinient way to set the required entry when shuting down the pods the entry is not removed when the pods are stopped possibly leading to an inaccessable metadata service.

cc @schlomo @klenkes74 @holgerkoch

**Comment by schlomo** [comment] 2018-05-30 18:08
Duplicate of #44 and possibly solved by #125 

IMHO the main question is to give the user control over the life cycle of the DNAT rule. Some users might want to keep it active to prevent IAM exposure in csase of kube2iam failures. Other users might want to get the previous cluster state back when kube2iam stops.

In any case, there will be cases where kube2iam *cannot* clean up the iptables configuration, e.g. because it crashed. So no matter which solution is implemented, we probably won't get a 100% reliable behavior.

**Comment by SharpEdgeMarshall** [comment] 2019-02-13 11:36
Please refer to #44

**Closed by SharpEdgeMarshall** 2019-02-13 11:36 UTC
Labels: duplicate
